const ADMIN_EMAIL_USERNAME_TEST_SUCCESS = "nvlong@outlook.com";
const ADMIN_PASSWORD_TEST_SUCCESS = "123";

const EMAIL_USERNAME_TEST_FAIL = "fail@mail.com";
const PASSWORD_TEST_FAIL = "123";

const CUSTOMER_EMAIL_USERNAME_TEST_SUCCESS = "user3@gmail.com";
const CUSTOMER_PASSWORD_TEST_SUCCESS = "123";

module.exports = {
    ADMIN_EMAIL_USERNAME_TEST_SUCCESS,
    ADMIN_PASSWORD_TEST_SUCCESS,
    CUSTOMER_EMAIL_USERNAME_TEST_SUCCESS,
    CUSTOMER_PASSWORD_TEST_SUCCESS,
    EMAIL_USERNAME_TEST_FAIL,
    PASSWORD_TEST_FAIL
}