name: Deploy to VPS

on:
  push:
    branches:
      - autoenvvar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH connection
        run: |
          ssh "${{ secrets.DO_VPS_DEPLOY_USER }}@${{ secrets.DO_VPS_PUBLIC_IP }}"
          "${{ secrets.DO_VPS_PASSWORD }}"

      - name: Copy .env to VPS
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          scp .env "${{ secrets.DO_VPS_DEPLOY_USER }}@${{ secrets.DO_VPS_PUBLIC_IP }}:/home/${{ secrets.DO_VPS_DEPLOY_USER }}/.env"
